basePath: /api/v1
host: localhost:3000
info:
  contact: {}
  description: Documentation Library API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger library API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
