basePath: /api/v1
definitions:
  accounts.CreateAccountRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  accounts.GetAccountResponse:
    properties:
      account_id:
        type: string
      created_at:
        type: string
      email:
        type: string
    type: object
  accounts.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  accounts.LoginResponse:
    properties:
      access_token:
        type: string
      account_id:
        type: string
      refresh_token:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Documentation Library API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger library API
  version: "1.0"
paths:
  /accounts/{account_id}:
    get:
      consumes:
      - application/json
      description: Get account details for a given ID.
      parameters:
      - description: Bearer Authorization Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accounts.GetAccountResponse'
        "404":
          description: User not found
        "500":
          description: Internal server error
      summary: Get account details
      tags:
      - Accounts
  /accounts/login:
    post:
      consumes:
      - application/json
      description: Authenticate user credentials.
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/accounts.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accounts.LoginResponse'
        "401":
          description: Invalid password
        "404":
          description: User not found
        "500":
          description: Internal server error
      summary: Authenticate user credentials
      tags:
      - Accounts
  /accounts/signup:
    post:
      consumes:
      - application/json
      description: Creates an account for a given email.
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/accounts.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Account successfully created
        "400":
          description: Could not parse request
        "409":
          description: User already registered
        "422":
          description: Request is well formed but contains invalid data
        "500":
          description: Internal server error
      summary: Creates an account
      tags:
      - Accounts
schemes:
- http
swagger: "2.0"
