version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:13.2
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
